import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import ToastProvider from "@/components/providers/toaster-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PavoLMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <ClerkProvider
            appearance={{
              baseTheme: dark,
              elements: {
                card: "bg-white text-accent-foreground dark:bg-background",
                headerTitle: "text-accent-foreground",
                headerSubtitle: "text-accent-foreground",
                dividerText: "text-accent-foreground",
                dividerLine: "bg-zinc-500/20",
                formFieldLabel: "text-accent-foreground",
                formFieldInput:
                  "text-accent-foreground border-zinc-500/20 bg-transparent",
                formButtonPrimary: "bg-primary",
                socialButtonsBlockButton:
                  "text-accent-foreground border-zinc-500/20",
                userButtonPopoverCard:
                  "bg-white text-accent-foreground dark:bg-background dark:border-[1px] dark:border-zinc-500/20",
                userButtonPopoverActionButtonIcon: "text-primary",
                userPreviewMainIdentifier: "text-accent-foreground",
                userPreviewSecondaryIdentifier: "text-primary",
                userButtonPopoverActionButtonText: "text-accent-foreground",
                userButtonPopoverFooter: "text-primary d-hidden",
                footerActionText: "text-accent-foreground",
                footerActionLink: "text-primary",
              },
            }}
          >
            <ToastProvider />
            {children}
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
